### ISSUE TITLE
OpenDAP for downloading of extents

### ISSUE THREAD

**Issue by samuelbosch** [lifewatch/sdmpredictors#1]
Suggestion by Jorge Assis:

One point I see since the beginning that could be improved is the way the data is imported to the R session. If a user has his study region clearly defined (e.g., Caribbean Sea), the package as is obligates him to download the global extent. We could think about creating netcdf files that would allow the package to work in opendap. This way the user would be asked to choose his extent and the data provided would only correspond to that.

**Comment by samuelbosch** [comment]
After short investigation the implications are:
- setting up an OpenDAP server
- converting files
- changing the way files are downloaded and cached

Or writing a custom service for clipping serverside.

**Comment by samuelbosch** [comment]
Regarding serving netcdf files, we should consider using [netcdf4 compression](http://www.unidata.ucar.edu/blogs/developer/entry/netcdf_compression).

**Comment by salvafern** [comment]
Bio-Oracle v3 will serve NetCDF files from an ERDDAP server. We may see if we continue using the 2D approach for the layers in sdmpredictors (for example: export layers as .tif using ERDDAP and feed to sdmpredictors), or develop a new approach to serve multidimensional datasets. Most likely we will go for the first option.

**Comment by salvafern** [comment]
Closing for now. Bio-Oracle v3 will be served in a separate package: https://github.com/bio-oracle/biooracler. It will use ERDDAP as backbone.
