### ISSUE TITLE
HTTP status was '404 Not Found' for BO21_chlomean_bdmin

### ISSUE THREAD

**Issue by jflowernet** [lifewatch/sdmpredictors#20]
I'm getting a 404 not found error when running:
`load_layers("BO21_chlomean_bdmin")`

Full error: 
`trying URL 'https://bio-oracle.org/data/2.2/Present.Benthic.Min.Depth.Chlorophyll.Min.BOv2_1.tif.zip'
Error in utils::download.file(layer_url, path, method = "auto", quiet = FALSE,  : 
  cannot open URL 'https://bio-oracle.org/data/2.2/Present.Benthic.Min.Depth.Chlorophyll.Min.BOv2_1.tif.zip'
In addition: Warning message:
In utils::download.file(layer_url, path, method = "auto", quiet = FALSE,  :
  cannot open URL 'https://bio-oracle.org/data/2.2/Present.Benthic.Min.Depth.Chlorophyll.Min.BOv2_1.tif.zip': HTTP status was '404 Not Found'`

I get the same error if I try to download direct from my browser by pasting the url.

All the other benthic layers I am loading download without a problem.

Many thanks for the amazing Bio-oracle layers and the sdmpredictors package! They are incredibly useful.

**Comment by salvafern** [comment]
Hi @jflowernet, thanks for raising the issue. Indeed there were some problems with the URLs. I have fixed these now and added a test to check the http status of the URLs. I'll do some additional checks tomorrow and push to CRAN if everything is ok.

**Comment by jflowernet** [comment]
Many thanks @salvafern ! I installed the Github version of the package and the url works now. Your tip about increasing download timeout from issue #18 was also useful as I was having this problem.
Thanks again
