### ISSUE TITLE
Error loading "BO22_RCP45_2100_tempmean_bdmax"

### ISSUE THREAD

**Issue by jflowernet** [lifewatch/sdmpredictors#22]
`load_layers("BO22_RCP45_2100_tempmean_bdmax")` gives this error:

`Error in .local(.Object, ...) : 
Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create a RasterLayer object from this file. (file does not exist)`

But the direct url for this dataset (https://bio-oracle.org/data/2.2/2100AOGCM.RCP45.Benthic.Max.Depth.Temperature.Max.BOv2_2.tif.zip) seems to work fine, and once renamed and placed in my datadir, the raster using loads fine using `load_layers().`

Not sure what is wrong, but wanted to flag it.

Thanks!

**Comment by salvafern** [comment]
Hi @jflowernet 

I'm not being able to replicate the issue:

``` r
library(sdmpredictors)
layer <- load_layers("BO22_RCP45_2100_tempmean_bdmax", datadir = ".")
#> trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/sdmpredictors_0.2.12.zip'
#> Content type 'application/zip' length 1438900 bytes (1.4 MB)
#> downloaded 1.4 MB

packageVersion("sdmpredictors")
#> [1] '0.2.12'
```

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Most likely is a version issue. Can you check if you are using the latest version (0.2.12)?

If not reinstall and retry. If the problem persists:
* Can you send me a `sessionInfo()`?
* Can you debug via `debug(sdmpredictors::load_layers)` and let me know where did the code fail?

**Comment by jflowernet** [comment]
Hmm, I can't replicate the problem; the layer is loading fine today.  Apologies for the false alarm, and thanks for the excellent pacakge!
