### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [lifewatch/sdmpredictors#23]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by salvafern** [comment]
Thank you for the heads up. I will fix it as soon as possible.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`sdmpredictors` imports 'rgdal'  using `rgdal::GDALis3ormore` as found by `pkgapi`, bulk imported in NAMESPACE, used in R/load.R line 112. The package imports `raster`, which itself imports `terra`, so `terra::gdal` provides the version of GDAL (`raster::projectRaster` uses `terra::project` I think). Please fix best by June, latest by October 2023.

**Comment by rsbivand** [comment]
@salvafern @bart-v @samuelbosch See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by salvafern** [comment]
Apologies for the delay. The dependency on `rgdal` has been replaced by `terra`. Thank you for raising this and pointing out the solution @rsbivand
