### ISSUE TITLE
Error in file download due to timeout limit

### ISSUE THREAD

**Issue by shirasal** [lifewatch/sdmpredictors#24]
While running
`sdmpredictors::load_layers(layercodes = c("BO_sstmean", "BO2_salinitymean_ss", "BO22_ppmean_ss"))`
I encountered an error. The first file (BO_sstmean) was downloaded while the others failed.
The error message I received was:
```
trying URL 'https://bio-oracle.org/data/1.0/BO_sstmean.zip'
Content type 'application/zip' length 13763101 bytes (13.1 MB)
downloaded 13.1 MB

trying URL 'https://bio-oracle.org/data/2.0/Present.Surface.Salinity.Mean.tif.zip'
Content type 'application/zip' length 51581905 bytes (49.2 MB)
downloaded 38.7 MB

Error in utils::download.file(layer_url, path, method = "auto", quiet = FALSE,  : 
  download from 'https://bio-oracle.org/data/2.0/Present.Surface.Salinity.Mean.tif.zip' failed
In addition: Warning messages:
1: In utils::download.file(layer_url, path, method = "auto", quiet = FALSE,  :
  downloaded length 40570760 != reported length 51581905
2: In utils::download.file(layer_url, path, method = "auto", quiet = FALSE,  :
  URL 'https://bio-oracle.org/data/2.0/Present.Surface.Salinity.Mean.tif.zip': Timeout of 60 seconds was reached
```

The problem was with the timeout limit, as the files were taking too long to download.
The solution was to run this line of code:
`options(timeout = max(300, getOption("timeout")))`
before running the function.

This is different to #14  where the error was caused by some peer certificate issue.

```
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
```

Hope this will help others

**Comment by salvafern** [comment]
Hi @shirasal 

Thanks for posting the solution! This can indeed help others. 

I could implement some option for the specific timeout of this package and let it be larger than 60 by default, but your solution seems also valid to me. We'll let it be for now 😄
